server:
  port: 8084

spring:
  application:
    name: neo4j-app
  cloud:
    discovry:
      enabled: false
  data:
    neo4j:
      password: test
      uri: bolt://localhost
      username: neo4j

logging:
  level:
    org:
      neo4j:
        driver:
          Driver: debug
          GraphDatabase: debug
          InboundMessageDispatcher: debug
          OutboundMessageHandler: debug
